name: first-github-action
on: [push]
jobs:
  install-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.HOST }}
          user: github
          key: ${{ secrets.PRIVATE_KEY}}




# https://zellwk.com/blog/github-actions-deploy/
# https://zellwk.com/blog/understanding-github-actions/